- name: Create Redmine persistent data folders
  file:
    path: /opt/redmine/files
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
  become: true

- name: Create Redmine config directory
  file:
    path: /opt/redmine/config
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
  become: true

- name: Generate Redmine database.yml from template
  template:
    src: templates/database.yml.j2
    dest: /opt/redmine/config/database.yml
    owner: 1000
    group: 1000
    mode: '0644'
  become: true

- name: Generate docker-compose.yml from template
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/redmine/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Launch Docker Compose stack
  shell: docker-compose -f /opt/redmine/docker-compose.yml up -d
  args:
    chdir: /opt/redmine
  become: true

- name: Wait for Redmine container to be ready
  shell: docker ps | grep redmine-redmine-1
  register: redmine_status
  retries: 10
  delay: 5
  until: redmine_status.rc == 0
  become: true
