version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    user: "root"
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/prometheus/data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /opt/grafana:/var/lib/grafana
      - /opt/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD={{ grafana_admin_password }}

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    ports:
      - "9100:9100"

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    restart: always
    ports:
      - "9115:9115"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://admin_redmine:Shikan244@redminedb.c3mk2a2gmfsa.eu-west-3.rds.amazonaws.com:5432/redminedb?sslmode=disable"
    ports:
      - "9187:9187"