global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.0.3.232:9100', '10.0.2.226:9100']

  - job_name: 'blackbox-exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://10.0.2.226:3000
        - http://10.0.3.232:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.3.232:9115

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['prometheus-postgres-exporter-1:9187']

